# Site settings
baseurl = "./"
languageCode = "en"
title = "Joshua Mangiola"
theme = "hugo-theme-cactus-plus"
googleAnalytics = "your_google_analytics_id"
# Set the value to true if your site include CJK (Chinese, Japanese, and Korean languages) characters
hasCJKLanguage = false

[params]
	author = "Joshua Mangiola"
	description = "Site Description"
	bio = "TypeScript and .NET Developer"

	twitter = "joshm998"
	facebook = "your_facebook_id"

	enableRSS = false
	enableToc = true

	enableDisqus = true
	disqusShortname = "joshmangiola"


	enableSummary = true
	# Set the value to true if use description in post front matter replace content summary
	useDescriptionReplaceSummary = true


	enableGoogleAnalytics = true
	enableBaiduAnalytics = false
	enableTwitterCard = false

	# Add custom assets with their paths relative to the static folder
	customCSS = []
	customJS  = []

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = ""
	about = ""
	archive = ""
	subscribe = ""

	olderPosts = ""
	newerPosts = ""
	copyright = ""

	# show latest posts in single page
	showLatestPosts = false
	readMore = ""

	# Share
	enableShare = true
	tweet = ""
	share = ""

	# 404 page
	title404 = ""
	subtitle404 = ""

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "font-awesome"
  # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
  socialIconStyle = ""


# Add additional social link entries underneath
[social]
	twitter-square = "https://www.twitter.com/joshm998"
	github-square = "https://www.github.com/joshuamangiola" 
	linkedin-square = "https://www.linkedin.com/in/joshua-mangiola/"
